### ISSUE TITLE
default.rteconfig utilities 

### ISSUE THREAD

**Issue by rhDEVFORLIFE** [ARM-software/cmsis-pack-eclipse-prebuilt#1]
Hello,

After using cmsis-pack-eclipse-prebuilt plugins a have a question in mind: 
how can i use default.rteconfig as in entry to Tools development (in order to
prepare project with integration of configured components )

I look forward to your answer.

**Comment by edriouk** [comment]
Hello,
What you currently see is a pre-release version of the plug-in (0.9.0). It contains only basic functionality showing how to access information stored in packs. 
Currently we are working on the release version of the plug-in (1.0.0). 
It will contain the functionality to create and manage CMSIS projects.
The release version should be available in a few weeks. 
Best regards,
Evgueni

**Comment by rhDEVFORLIFE** [comment]
Hello,

The new functionality " create and manage CMSIS projects" can be used by different
IDE tools in the market example (KEIL, IAR,...) ? and  generating based project with the configuration defined in default.rteconfig  ?

Best regards,
rhDEVFORLIFE

**Comment by edriouk** [comment]
The Eclipse plug-in will demonstrate creating/updating CDT projects based on CMSIS RTE configuration. Thus Eclipse-based IDEs could potentially use the pre-build plug-in as is, but in most cases they would require some adjustments.
Non-Eclipse IDEs could make use of algorithms implemented in the plug-in (Java source code is available). For example, Keil MDK-ARM uses almost the same algorithms, but implemented in C++.  
In fact one of the main goals of the plug-in is to publish a reference implementation the algorithms to allow different tools work consistently.

**Comment by rhDEVFORLIFE** [comment]
Thank's a lot edriouk for the clarification.
